---
- name: create ~/.kube directory
  ansible.builtin.file:
    path: "{{ item }}/.kube"
    state: directory
  with_items:
    - "/home/vagrant"
    - "/root"

- name: copy kubernetes config for root user 
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    mode: 0400
    remote_src: true
  with_items:
    - { path: "/root/.kube/config", owner: "root" }
    - { path: "/home/vagrant/.kube/config", owner: "vagrant" }
