---
- name: generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command

- name: copy join command
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join"
  become: false
